var myapp=angular.module("myapp",["ionic"]);

     myapp.config(function($stateProvider,$urlRouterProvider){
 	$stateProvider
 	//一级路由
 	.state("table",{
	 		url:"/tabs",
	 		abstract:true,
	 		templateUrl:"templates/tabs/tabs.html"
 	})
 	//二级路由
 	.state("tabs.home",{
 		url:"/home",
 		views:{"table-home":{
 			templateUrl:"templates/home/home.html"
 		}} 		
 	})
 	.state("tabs.home",{
 		url:"/muji",
 		views:{"table-home":{
 			templateUrl:"templates/muji/muji.html"
 		}} 		
 	})
 	.state("cart",{
 		url:"/cart",
 		templateUrl:"templates/cart/cart.html"
 		controller:"cartCtrl"
 	})
 	.state("table.detail",{
 		url:"/detail?:text",
 		views{
 			"tab-categroy":{
 				templateUrl:"templates/detail/detail.html",
 				controller:"detailCtrl"
 			}}
 	})
 	.state("table.master",{
 		url:"/master",
 		views{"tab-master":{
 				templateUrl:"templates/master/master.html",
 				controller:"masterCtrl"
 		}}
 	})
 	.state("table.information",{
 		url:"/information?:name",
 		views{"table-master":{
 			templateUrl:"templates/information/information.html",
 			controller:"informationCtrl"
 		}}
 	})
 	.state("table.share",{
 		url:"/share",
 		views{"table-share":{
 			templateUrl:"templates/share/share.html",
 			controller:"shareCtrl"
 		}}
 	})
 	.state("table.share_detail",{
 		url:"/share_detail?:name",
 		views{"table-share":{
 			templateUrl:"templates/share_detail/share_detail.html",
 			controller:"share_detailCtrl"
 		}}
 	})
 	.state("table.personal",{
 		url:"/personal",
 		views:{"table-personal":{
 			templateUrl:"templates/personal/personal.html"
 		}}
 	})
 	.state("slide",{
 		url:"/slide",
 		templateUrl:"templates/slide/slide.html"
 	})
 	//默认URL首页
 	$urlRouterProvider.otherwise("/slide")
 })
